import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavBar from "@/components/menus/MainNavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white dark:bg-black`}>
        <Providers>
          <NextAuthProvider session={session}>
            <MainNavBar />
            {children}
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
